### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by ikb42** [faye/websocket-driver-node#38]
Hi

I'm getting this error which seems to occur after a connection has closed.  
It doesn't occur on node 8.15.0, but does on 12.16.1.

How can I catch this / manage it?

Thanks!

Node version: 12.16.1
Driver version: 0.7.3

`Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:780:11)
    at Socket._write (net.js:792:8)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Socket.Writable.write (_stream_writable.js:316:11)
    at IO.ondata (internal/streams/legacy.js:19:31)
    at IO.emit (events.js:311:20)
    at IO.EventEmitter.emit (domain.js:482:12)
    at Hybi._write (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/base.js:158:25)
    at Hybi._sendFrame (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:270:10)
    at Hybi.onMessageReady (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:225:12)
    at Hybi.frame (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:234:22)
    at Hybi.<anonymous> (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:180:48)
    at /var/www/app/node_modules/websocket-extensions/lib/pipeline/index.js:26:51
    at Pledge.then (/var/www/app/node_modules/websocket-extensions/lib/pipeline/pledge.js:27:23)
    at Pipeline.close (/var/www/app/node_modules/websocket-extensions/lib/pipeline/index.js:26:24)
    at Extensions.close (/var/www/app/node_modules/websocket-extensions/lib/websocket_extensions.js:142:20)
    at Hybi.close (/var/www/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:180:24)
    at SocketDrivers.close (/var/www/app/server/socket/socket-drivers.js:396:27)
    at Socket.<anonymous> (/var/www/app/server/socket/socket-server.js:463:23)
    at Socket.emit (events.js:323:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}`

**Comment by jcoglan** [comment]
Can you provide a small self-contained example of a server that demonstrates this error?

**Comment by ikb42** [comment]
@jcoglan it doesn't happen all the time unfortunately, and I haven't been able to make it happen on demand.
If I could catch it I might be able to figure out how to make it happen, then could give an example app.

**Comment by ikb42** [comment]
@jcoglan spent some more time on this and I can make it happen and catch it too.
It only happens when used via nginx as a reverse proxy.
I don't think this is a problem with the driver, I'll close.  If you'd still like an example please let me know.

**Comment by jcoglan** [comment]
This is potentially a grey area since this package is only supposed to be concerned with the _data_ of the WebSocket protocol and not _how that data is transferred_, which is why it implements the stream interface for connecting to TCP. However if there's something about the way the stream abstraction propagates errors that means we need to revisit that design then do add your thoughts to this thread.
